###**1.5 넘파이**

**1.5.1 넘파이 가져오기**

In [1]:
import numpy as np

**1.5.2 넘파이 배열 생성하기**

In [2]:
x = np.array([1.0, 2.0, 3.0])

print(x, type(x))

[1. 2. 3.] <class 'numpy.ndarray'>


**1.5.3 넘파이의 산술 연산**

In [3]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

print(x + y) # 원소별 덧셈
print(x - y)
print(x * y) # 원소별 곱셈(element-wise product)
print(x / y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [4]:
x = np.array([1.0, 2.0, 3.0])

print(x / 20)

[0.05 0.1  0.15]


**1.5.4 넘파이의 N차원 배열**

In [6]:
A = np.array([[1, 2], [3, 4]])

print(A)
print(A.shape)
print(A.dtype)

[[1 2]
 [3 4]]
(2, 2)
int64


In [7]:
B = np.array([[3, 0], [0, 6]])

print(A + B)
print(A * B)

[[ 4  2]
 [ 3 10]]
[[ 3  0]
 [ 0 24]]


In [8]:
print(A)
print(A * 10)

[[1 2]
 [3 4]]
[[10 20]
 [30 40]]


**1.5.5 브로드캐스트**
- shape이 다른 넘파이 배열끼리의 연산을 도와주는 기능

In [9]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])

print(A * B) # B를 [[10, 20], [10, 20]]으로 변환 후 계산

[[10 40]
 [30 80]]


**1.5.6 원소 접근**

In [10]:
X = np.array([[51, 55], [14, 19], [0, 4]])

print(X)
print(X[0]) # 0행
print(X[0][1]) # (0, 1) 위치의 원소

[[51 55]
 [14 19]
 [ 0  4]]
[51 55]
55


In [11]:
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


In [12]:
X = X.flatten() # X를 1차원 배열로 변환(평탄화)

print(X)
print(X[np.array([0, 2, 4])]) # 인덱스가 0, 2, 4인 원소 얻기

[51 55 14 19  0  4]
[51 14  0]


In [13]:
print(X > 15)
print(X[X > 15])

[ True  True False  True False False]
[51 55 19]
